# Generated by Django 5.2 on 2025-07-11 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_baner', models.CharField(max_length=50)),
                ('price_baner', models.IntegerField()),
                ('image_baner', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('description_baner', models.TextField()),
                ('published_date_baner', models.DateField()),
                ('author_baner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('category_baner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
        ),
    ]
